// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// KL_Cox_Estimate_cpp
arma::vec KL_Cox_Estimate_cpp(const double N, const arma::mat& Z, const arma::vec& delta, const arma::vec& delta_eta, const arma::vec& n_each_stratum, const double eta, arma::vec beta_initial, const double tol, const int maxit, const double lambda, bool backtrack, bool message);
RcppExport SEXP _SurvBregDiv_KL_Cox_Estimate_cpp(SEXP NSEXP, SEXP ZSEXP, SEXP deltaSEXP, SEXP delta_etaSEXP, SEXP n_each_stratumSEXP, SEXP etaSEXP, SEXP beta_initialSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP lambdaSEXP, SEXP backtrackSEXP, SEXP messageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type N(NSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta_eta(delta_etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_initial(beta_initialSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type backtrack(backtrackSEXP);
    Rcpp::traits::input_parameter< bool >::type message(messageSEXP);
    rcpp_result_gen = Rcpp::wrap(KL_Cox_Estimate_cpp(N, Z, delta, delta_eta, n_each_stratum, eta, beta_initial, tol, maxit, lambda, backtrack, message));
    return rcpp_result_gen;
END_RCPP
}
// pl_cal_exact
double pl_cal_exact(const arma::vec& lp, const arma::vec& delta, const arma::vec& time, const arma::vec& n_each_stratum, const double comb_max);
RcppExport SEXP _SurvBregDiv_pl_cal_exact(SEXP lpSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP n_each_stratumSEXP, SEXP comb_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type lp(lpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const double >::type comb_max(comb_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(pl_cal_exact(lp, delta, time, n_each_stratum, comb_max));
    return rcpp_result_gen;
END_RCPP
}
// calculateWTilde_exact
arma::mat calculateWTilde_exact(const arma::mat& Z, const arma::vec& delta, const arma::vec& time, const arma::vec& n_each_stratum, const arma::vec& external_beta, const double comb_max);
RcppExport SEXP _SurvBregDiv_calculateWTilde_exact(SEXP ZSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP n_each_stratumSEXP, SEXP external_betaSEXP, SEXP comb_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type external_beta(external_betaSEXP);
    Rcpp::traits::input_parameter< const double >::type comb_max(comb_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateWTilde_exact(Z, delta, time, n_each_stratum, external_beta, comb_max));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_exact_KL
Rcpp::List ddloglik_exact_KL(const arma::mat& Z, const arma::vec& delta, const arma::vec& time, const arma::vec& beta, const arma::vec& n_each_stratum, const arma::mat& tildeW, const double eta, const double comb_max);
RcppExport SEXP _SurvBregDiv_ddloglik_exact_KL(SEXP ZSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP betaSEXP, SEXP n_each_stratumSEXP, SEXP tildeWSEXP, SEXP etaSEXP, SEXP comb_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tildeW(tildeWSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type comb_max(comb_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_exact_KL(Z, delta, time, beta, n_each_stratum, tildeW, eta, comb_max));
    return rcpp_result_gen;
END_RCPP
}
// CoxKL_NR_exact
arma::vec CoxKL_NR_exact(const arma::mat& Z, const arma::vec& delta, const arma::vec& time, const arma::vec& n_each_stratum, const arma::mat& tildeW, double eta, arma::vec beta, double tol, int max_iter, double comb_max);
RcppExport SEXP _SurvBregDiv_CoxKL_NR_exact(SEXP ZSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP n_each_stratumSEXP, SEXP tildeWSEXP, SEXP etaSEXP, SEXP betaSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP comb_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tildeW(tildeWSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type comb_max(comb_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(CoxKL_NR_exact(Z, delta, time, n_each_stratum, tildeW, eta, beta, tol, max_iter, comb_max));
    return rcpp_result_gen;
END_RCPP
}
// calculateWTilde_breslow
arma::mat calculateWTilde_breslow(const arma::mat& Z, const arma::vec& delta, const arma::vec& time, const arma::vec& risk_score_ext, const arma::vec& n_each_stratum);
RcppExport SEXP _SurvBregDiv_calculateWTilde_breslow(SEXP ZSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP risk_score_extSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type risk_score_ext(risk_score_extSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateWTilde_breslow(Z, delta, time, risk_score_ext, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// pl_cal_breslow
double pl_cal_breslow(const arma::vec& lp, const arma::vec& delta, const arma::vec& time, const arma::vec& n_each_stratum);
RcppExport SEXP _SurvBregDiv_pl_cal_breslow(SEXP lpSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type lp(lpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(pl_cal_breslow(lp, delta, time, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_breslow_KL
Rcpp::List ddloglik_breslow_KL(const arma::mat& Z, const arma::vec& delta, const arma::vec& time, const arma::vec& beta, const arma::vec& n_each_stratum, const arma::mat& Wtilde, const double eta);
RcppExport SEXP _SurvBregDiv_ddloglik_breslow_KL(SEXP ZSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP betaSEXP, SEXP n_each_stratumSEXP, SEXP WtildeSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Wtilde(WtildeSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_breslow_KL(Z, delta, time, beta, n_each_stratum, Wtilde, eta));
    return rcpp_result_gen;
END_RCPP
}
// CoxKL_NR_breslow
arma::vec CoxKL_NR_breslow(const arma::mat& Z, const arma::vec& delta, const arma::vec& time, const arma::vec& n_each_stratum, const arma::mat& Wtilde, const double eta, arma::vec beta, double tol, int max_iter);
RcppExport SEXP _SurvBregDiv_CoxKL_NR_breslow(SEXP ZSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP n_each_stratumSEXP, SEXP WtildeSEXP, SEXP etaSEXP, SEXP betaSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Wtilde(WtildeSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(CoxKL_NR_breslow(Z, delta, time, n_each_stratum, Wtilde, eta, beta, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// KL_Cox_highdim
List KL_Cox_highdim(const arma::mat& Z, const arma::vec& delta, const arma::vec& delta_tilde, const double& eta, const arma::vec& n_each_stratum, arma::vec& beta, const arma::vec& K1, const int& K0, const arma::vec& lambda_seq, const double& alpha, bool lambda_early_stop, double stop_loss_ratio, const arma::vec& group_multiplier, const int& max_total_iter, const int& max_each_iter, const double& tol, const int& initial_active_group, const double& nvar_max, const double& group_max, const bool& trace_lambda, const bool& actSet, const int& actIter, const int& activeGroupNum, const bool& actSetRemove);
RcppExport SEXP _SurvBregDiv_KL_Cox_highdim(SEXP ZSEXP, SEXP deltaSEXP, SEXP delta_tildeSEXP, SEXP etaSEXP, SEXP n_each_stratumSEXP, SEXP betaSEXP, SEXP K1SEXP, SEXP K0SEXP, SEXP lambda_seqSEXP, SEXP alphaSEXP, SEXP lambda_early_stopSEXP, SEXP stop_loss_ratioSEXP, SEXP group_multiplierSEXP, SEXP max_total_iterSEXP, SEXP max_each_iterSEXP, SEXP tolSEXP, SEXP initial_active_groupSEXP, SEXP nvar_maxSEXP, SEXP group_maxSEXP, SEXP trace_lambdaSEXP, SEXP actSetSEXP, SEXP actIterSEXP, SEXP activeGroupNumSEXP, SEXP actSetRemoveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta_tilde(delta_tildeSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type K1(K1SEXP);
    Rcpp::traits::input_parameter< const int& >::type K0(K0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda_seq(lambda_seqSEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type lambda_early_stop(lambda_early_stopSEXP);
    Rcpp::traits::input_parameter< double >::type stop_loss_ratio(stop_loss_ratioSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type group_multiplier(group_multiplierSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_total_iter(max_total_iterSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_each_iter(max_each_iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type initial_active_group(initial_active_groupSEXP);
    Rcpp::traits::input_parameter< const double& >::type nvar_max(nvar_maxSEXP);
    Rcpp::traits::input_parameter< const double& >::type group_max(group_maxSEXP);
    Rcpp::traits::input_parameter< const bool& >::type trace_lambda(trace_lambdaSEXP);
    Rcpp::traits::input_parameter< const bool& >::type actSet(actSetSEXP);
    Rcpp::traits::input_parameter< const int& >::type actIter(actIterSEXP);
    Rcpp::traits::input_parameter< const int& >::type activeGroupNum(activeGroupNumSEXP);
    Rcpp::traits::input_parameter< const bool& >::type actSetRemove(actSetRemoveSEXP);
    rcpp_result_gen = Rcpp::wrap(KL_Cox_highdim(Z, delta, delta_tilde, eta, n_each_stratum, beta, K1, K0, lambda_seq, alpha, lambda_early_stop, stop_loss_ratio, group_multiplier, max_total_iter, max_each_iter, tol, initial_active_group, nvar_max, group_max, trace_lambda, actSet, actIter, activeGroupNum, actSetRemove));
    return rcpp_result_gen;
END_RCPP
}
// Cox_NR
List Cox_NR(const arma::mat& Z, const arma::vec& delta, const arma::vec& time, const arma::vec& n_each_stratum, arma::vec beta, int ties_method, double tol, int max_iter, double comb_max);
RcppExport SEXP _SurvBregDiv_Cox_NR(SEXP ZSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP n_each_stratumSEXP, SEXP betaSEXP, SEXP ties_methodSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP comb_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type ties_method(ties_methodSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type comb_max(comb_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(Cox_NR(Z, delta, time, n_each_stratum, beta, ties_method, tol, max_iter, comb_max));
    return rcpp_result_gen;
END_RCPP
}
// Cox_MDTL_cpp
arma::vec Cox_MDTL_cpp(const double N, const arma::mat& Z, const arma::vec& delta, const arma::vec& n_each_stratum, const double eta, const arma::vec& external_beta, const arma::mat& Q, const arma::vec& beta_initial, const double lambda, const double tol, const int max_iter, bool backtrack, bool message);
RcppExport SEXP _SurvBregDiv_Cox_MDTL_cpp(SEXP NSEXP, SEXP ZSEXP, SEXP deltaSEXP, SEXP n_each_stratumSEXP, SEXP etaSEXP, SEXP external_betaSEXP, SEXP QSEXP, SEXP beta_initialSEXP, SEXP lambdaSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP backtrackSEXP, SEXP messageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type N(NSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type external_beta(external_betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_initial(beta_initialSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< bool >::type backtrack(backtrackSEXP);
    Rcpp::traits::input_parameter< bool >::type message(messageSEXP);
    rcpp_result_gen = Rcpp::wrap(Cox_MDTL_cpp(N, Z, delta, n_each_stratum, eta, external_beta, Q, beta_initial, lambda, tol, max_iter, backtrack, message));
    return rcpp_result_gen;
END_RCPP
}
// cox_MDTL_enet_cpp
List cox_MDTL_enet_cpp(const arma::vec& delta, const arma::mat& Z, const arma::vec& n_each_prov, arma::vec& beta, const int K0, const arma::vec& K1, const arma::vec& lambda_seq, const bool lambda_early_stop, const double stop_loss_ratio, const arma::vec& group_multiplier, const int max_total_iter, const int max_each_iter, const double tol, const int initial_active_group, const double nvar_max, const double group_max, const bool trace_lambda, const bool actSet, const int actIter, const int activeGroupNum, const bool actSetRemove, const double alpha, const double eta_mdtl, const arma::mat& vcov, const arma::vec& Qbeta_ext);
RcppExport SEXP _SurvBregDiv_cox_MDTL_enet_cpp(SEXP deltaSEXP, SEXP ZSEXP, SEXP n_each_provSEXP, SEXP betaSEXP, SEXP K0SEXP, SEXP K1SEXP, SEXP lambda_seqSEXP, SEXP lambda_early_stopSEXP, SEXP stop_loss_ratioSEXP, SEXP group_multiplierSEXP, SEXP max_total_iterSEXP, SEXP max_each_iterSEXP, SEXP tolSEXP, SEXP initial_active_groupSEXP, SEXP nvar_maxSEXP, SEXP group_maxSEXP, SEXP trace_lambdaSEXP, SEXP actSetSEXP, SEXP actIterSEXP, SEXP activeGroupNumSEXP, SEXP actSetRemoveSEXP, SEXP alphaSEXP, SEXP eta_mdtlSEXP, SEXP vcovSEXP, SEXP Qbeta_extSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_prov(n_each_provSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const int >::type K0(K0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type K1(K1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda_seq(lambda_seqSEXP);
    Rcpp::traits::input_parameter< const bool >::type lambda_early_stop(lambda_early_stopSEXP);
    Rcpp::traits::input_parameter< const double >::type stop_loss_ratio(stop_loss_ratioSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type group_multiplier(group_multiplierSEXP);
    Rcpp::traits::input_parameter< const int >::type max_total_iter(max_total_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type max_each_iter(max_each_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type initial_active_group(initial_active_groupSEXP);
    Rcpp::traits::input_parameter< const double >::type nvar_max(nvar_maxSEXP);
    Rcpp::traits::input_parameter< const double >::type group_max(group_maxSEXP);
    Rcpp::traits::input_parameter< const bool >::type trace_lambda(trace_lambdaSEXP);
    Rcpp::traits::input_parameter< const bool >::type actSet(actSetSEXP);
    Rcpp::traits::input_parameter< const int >::type actIter(actIterSEXP);
    Rcpp::traits::input_parameter< const int >::type activeGroupNum(activeGroupNumSEXP);
    Rcpp::traits::input_parameter< const bool >::type actSetRemove(actSetRemoveSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type eta_mdtl(eta_mdtlSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type vcov(vcovSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Qbeta_ext(Qbeta_extSEXP);
    rcpp_result_gen = Rcpp::wrap(cox_MDTL_enet_cpp(delta, Z, n_each_prov, beta, K0, K1, lambda_seq, lambda_early_stop, stop_loss_ratio, group_multiplier, max_total_iter, max_each_iter, tol, initial_active_group, nvar_max, group_max, trace_lambda, actSet, actIter, activeGroupNum, actSetRemove, alpha, eta_mdtl, vcov, Qbeta_ext));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_indi
Rcpp::List ddloglik_indi(const arma::mat& Z, const arma::vec& delta, const arma::vec& beta, const arma::vec& weight, const arma::vec& n_each_stratum);
RcppExport SEXP _SurvBregDiv_ddloglik_indi(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP, SEXP weightSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_indi(Z, delta, beta, weight, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// Cox_indi
Rcpp::List Cox_indi(const arma::mat& Z, const arma::vec& delta, const arma::vec& weight, const arma::vec& n_each_stratum, arma::vec beta, double tol, int max_iter);
RcppExport SEXP _SurvBregDiv_Cox_indi(SEXP ZSEXP, SEXP deltaSEXP, SEXP weightSEXP, SEXP n_each_stratumSEXP, SEXP betaSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(Cox_indi(Z, delta, weight, n_each_stratum, beta, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// rev_cumsum
arma::vec rev_cumsum(const arma::vec& X);
RcppExport SEXP _SurvBregDiv_rev_cumsum(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(rev_cumsum(X));
    return rcpp_result_gen;
END_RCPP
}
// combn_index
arma::umat combn_index(int n, int r);
RcppExport SEXP _SurvBregDiv_combn_index(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(combn_index(n, r));
    return rcpp_result_gen;
END_RCPP
}
// pl_cal_theta
double pl_cal_theta(const arma::vec& lp, const arma::vec& delta, const arma::vec& n_each_stratum);
RcppExport SEXP _SurvBregDiv_pl_cal_theta(SEXP lpSEXP, SEXP deltaSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type lp(lpSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(pl_cal_theta(lp, delta, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// calculateDeltaTilde
arma::vec calculateDeltaTilde(const arma::vec& event, const arma::vec& time, const arma::vec& RS, const arma::vec& n_each_stratum);
RcppExport SEXP _SurvBregDiv_calculateDeltaTilde(SEXP eventSEXP, SEXP timeSEXP, SEXP RSSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type RS(RSSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateDeltaTilde(event, time, RS, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// loss_fn_cpp
List loss_fn_cpp(const arma::mat& Z, const arma::vec& delta, arma::vec& beta, const arma::vec& n_each_stratum);
RcppExport SEXP _SurvBregDiv_loss_fn_cpp(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_fn_cpp(Z, delta, beta, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_S0
List ddloglik_S0(const arma::mat& Z, const arma::vec& delta, const arma::vec& beta, const arma::vec& n_each_stratum);
RcppExport SEXP _SurvBregDiv_ddloglik_S0(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP, SEXP n_each_stratumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_S0(Z, delta, beta, n_each_stratum));
    return rcpp_result_gen;
END_RCPP
}
// cox_c_index
Rcpp::List cox_c_index(const arma::vec& time, const arma::vec& xbeta, const arma::vec& delta);
RcppExport SEXP _SurvBregDiv_cox_c_index(SEXP timeSEXP, SEXP xbetaSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xbeta(xbetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(cox_c_index(time, xbeta, delta));
    return rcpp_result_gen;
END_RCPP
}
// maxgrad
double maxgrad(arma::mat& x, arma::vec& r, arma::vec& K, arma::vec& m);
RcppExport SEXP _SurvBregDiv_maxgrad(SEXP xSEXP, SEXP rSEXP, SEXP KSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(maxgrad(x, r, K, m));
    return rcpp_result_gen;
END_RCPP
}
// maxgrad_MDTL
double maxgrad_MDTL(arma::mat& x, arma::vec& r, arma::vec& Qbeta_ext, arma::vec& Qbeta_Ustar, arma::vec& K, arma::vec& m, double eta);
RcppExport SEXP _SurvBregDiv_maxgrad_MDTL(SEXP xSEXP, SEXP rSEXP, SEXP Qbeta_extSEXP, SEXP Qbeta_UstarSEXP, SEXP KSEXP, SEXP mSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Qbeta_ext(Qbeta_extSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Qbeta_Ustar(Qbeta_UstarSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(maxgrad_MDTL(x, r, Qbeta_ext, Qbeta_Ustar, K, m, eta));
    return rcpp_result_gen;
END_RCPP
}
// Cox_Vcov
arma::mat Cox_Vcov(const arma::mat& Z, const arma::vec& delta, const arma::vec& beta, const arma::vec& n_each_stratum, const double lambda);
RcppExport SEXP _SurvBregDiv_Cox_Vcov(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP, SEXP n_each_stratumSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type n_each_stratum(n_each_stratumSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(Cox_Vcov(Z, delta, beta, n_each_stratum, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SurvBregDiv_KL_Cox_Estimate_cpp", (DL_FUNC) &_SurvBregDiv_KL_Cox_Estimate_cpp, 12},
    {"_SurvBregDiv_pl_cal_exact", (DL_FUNC) &_SurvBregDiv_pl_cal_exact, 5},
    {"_SurvBregDiv_calculateWTilde_exact", (DL_FUNC) &_SurvBregDiv_calculateWTilde_exact, 6},
    {"_SurvBregDiv_ddloglik_exact_KL", (DL_FUNC) &_SurvBregDiv_ddloglik_exact_KL, 8},
    {"_SurvBregDiv_CoxKL_NR_exact", (DL_FUNC) &_SurvBregDiv_CoxKL_NR_exact, 10},
    {"_SurvBregDiv_calculateWTilde_breslow", (DL_FUNC) &_SurvBregDiv_calculateWTilde_breslow, 5},
    {"_SurvBregDiv_pl_cal_breslow", (DL_FUNC) &_SurvBregDiv_pl_cal_breslow, 4},
    {"_SurvBregDiv_ddloglik_breslow_KL", (DL_FUNC) &_SurvBregDiv_ddloglik_breslow_KL, 7},
    {"_SurvBregDiv_CoxKL_NR_breslow", (DL_FUNC) &_SurvBregDiv_CoxKL_NR_breslow, 9},
    {"_SurvBregDiv_KL_Cox_highdim", (DL_FUNC) &_SurvBregDiv_KL_Cox_highdim, 24},
    {"_SurvBregDiv_Cox_NR", (DL_FUNC) &_SurvBregDiv_Cox_NR, 9},
    {"_SurvBregDiv_Cox_MDTL_cpp", (DL_FUNC) &_SurvBregDiv_Cox_MDTL_cpp, 13},
    {"_SurvBregDiv_cox_MDTL_enet_cpp", (DL_FUNC) &_SurvBregDiv_cox_MDTL_enet_cpp, 25},
    {"_SurvBregDiv_ddloglik_indi", (DL_FUNC) &_SurvBregDiv_ddloglik_indi, 5},
    {"_SurvBregDiv_Cox_indi", (DL_FUNC) &_SurvBregDiv_Cox_indi, 7},
    {"_SurvBregDiv_rev_cumsum", (DL_FUNC) &_SurvBregDiv_rev_cumsum, 1},
    {"_SurvBregDiv_combn_index", (DL_FUNC) &_SurvBregDiv_combn_index, 2},
    {"_SurvBregDiv_pl_cal_theta", (DL_FUNC) &_SurvBregDiv_pl_cal_theta, 3},
    {"_SurvBregDiv_calculateDeltaTilde", (DL_FUNC) &_SurvBregDiv_calculateDeltaTilde, 4},
    {"_SurvBregDiv_loss_fn_cpp", (DL_FUNC) &_SurvBregDiv_loss_fn_cpp, 4},
    {"_SurvBregDiv_ddloglik_S0", (DL_FUNC) &_SurvBregDiv_ddloglik_S0, 4},
    {"_SurvBregDiv_cox_c_index", (DL_FUNC) &_SurvBregDiv_cox_c_index, 3},
    {"_SurvBregDiv_maxgrad", (DL_FUNC) &_SurvBregDiv_maxgrad, 4},
    {"_SurvBregDiv_maxgrad_MDTL", (DL_FUNC) &_SurvBregDiv_maxgrad_MDTL, 7},
    {"_SurvBregDiv_Cox_Vcov", (DL_FUNC) &_SurvBregDiv_Cox_Vcov, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SurvBregDiv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
